// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from './components/Navbar'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//        <Navbar />
//          <main className="pt-[76px]">
//           {children}
//         </main>
//         </body>
//     </html>
//   );
// }


// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";
// import ConditionalLayout from './src/ConditionalLayout'

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body suppressHydrationWarning>
//         {/* <Navbar /> */}

//         {/* <main className=""> */}
//         <main className="pt-[76px] lg:pt-[116px]">
//         <ConditionalLayout>
//           {children}
//         </ConditionalLayout>
//         </main>
//           {/* <Footer /> */}
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import ConditionalLayout from "./src/ConditionalLayout";
import Preloader from './components/Preloader'
import AnimatedCursor from './components/AnimatedCursor'
import SocialMediaLine from './components/SocialMediaLine'

import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import Smoothscrollview from "./components/Smoothscrollview";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} lang="en">
      <body suppressHydrationWarning>
        {/* <body className={`${inter.variable} font-sans`}> */}
        {/* <Preloader/> */}
          {/* <Smoothscrollview/> */}
        <ConditionalLayout>
          {/* <AnimatedCursor/> */}
          {/* <SocialMediaLine/> */}
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
        </ConditionalLayout>
      </body>
    </html>
   
  );
}

 //  <html
    //   lang="en"
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    //   suppressHydrationWarning
    // >
    //   <body className="min-h-full">
    //     <ThemeProvider
    //       attribute="class"
    //       defaultTheme="light"
    //       enableSystem={false}
    //       disableTransitionOnChange
    //     >
    //       <ConditionalLayout>
    //         {children}
    //       </ConditionalLayout>
    //     </ThemeProvider>
    //   </body>
    // </html>